name: minimal-gnome-nvidia
description: "Bare-bones GNOME setup with Nvidia drivers"
base-image: ghcr.io/ublue-os/ucore-minimal
image-version: stable-nvidia 
 
modules:
  - type: rpm-ostree
    install:
      - gnome-shell
      - gnome-control-center
      - nautilus
      - gnome-terminal
      - mutter
      - gdm
      - xorg-x11-server-Xwayland
      
      - distrobox
      - virt-manager
      - qemu-kvm
      - libvirt
      - just
 
  - type: systemd
    user:
      enabled:
        - gdm.service
