name: minimal-gnome-nvidia
description: "Bare-bones GNOME setup with Nvidia drivers"
base-image: ghcr.io/ublue-os/base-nvidia
image-version: latest

modules:     
  - type: rpm-ostree
    install:
      - gnome-shell
      - gnome-control-center
      - nautilus
      - gnome-terminal
      - mutter
      - gdm
      - xorg-x11-server-Xwayland
      
      - distrobox
      - virt-manager
      - qemu-kvm
      - libvirt
      - just

      - plymouth
      - plymouth-theme-spinner
      
  - type: rpm-ostree
    remove:
      - firefox
      - firefox-langpacks
      - gnome-terminal
      - gnome-tour
      - htop
      - nvtop
      - malcontent
      - malcontent-control
      - malcontent-ui
  - type: script
    scripts:
     - setup-gui.sh

  - type: kargs
    kargs:
      - quiet
      - splash
      - rd.driver.pre=nvidia
      - nvidia-drm.modeset=1
